# Generated by Django 5.0.4 on 2024-04-27 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0002_paciente_cedula'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='cedula',
            field=models.CharField(default='valor_por_defecto', max_length=50, unique=True),
        ),
    ]
